# Site
title: ICE Raids Toolkit
description: Defend Against ICE Raids and Community Arrests
logo: idp.png                                                 # Site logo
locale: en_US

# Left Block Images
background:
  homepage: images/arrest.png
  post-list: images/court.jpg                     # this image will be shown on post list page
  default-post: images/prison.jpg           # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
